---
benchmark_config:
  generic:
    benchmark: postgresql
    cpus: 0
    skip_clear_page_cache: false
    transparent_hugepages: always
    overcommit_memory: never_check
  postgresql:
    record_count: 1000
    operation_count: 1000
    read_proportion: 0.50
    update_proportion: 0.50
    insert_proportion: 0.00
    rmw_proportion: 0.00
    scan_proportion: 0.00
    delete_proportion: 0.00
    request_distribution: "uniform"
    thread_count: 4
    target: 1000
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: false
    hooks:
      - mm_rss_stat
      - process_trace
      - madvise
      - perf
      - unmap_range
      - vfs_read
      - vfs_write
